name: lottie_native
description: Render lottie animations, using the native platform libraries.
version: 0.1.0
repository: https://github.com/programmierbar/lottie_native
issue_tracker: https://github.com/programmierbar/lottie_native/issues

environment:
  sdk: ^2.19.0
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  melos: ^3.1.0

flutter:
  plugin:
    platforms:
      android:
        package: de.lotum.lottie_native
        pluginClass: LottieNativePlugin
      ios:
        pluginClass: LottieNativePlugin
